# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/shift_ram_IP_2/shift_ram_IP_2.xci
# IP: The module: 'shift_ram_IP_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/shift_ram_IP_2/shift_ram_IP_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram_IP_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/shift_ram_IP_2/shift_ram_IP_2.xci
# IP: The module: 'shift_ram_IP_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/shift_ram_IP_2/shift_ram_IP_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram_IP_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
