# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16.xci
# IP: The module: 'frame_fifo_w17xd16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo_w17xd16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo_w17xd16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo_w17xd16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16.xci
# IP: The module: 'frame_fifo_w17xd16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo_w17xd16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo_w17xd16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/frame_fifo_w17xd16/frame_fifo_w17xd16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_fifo_w17xd16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
