# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/ddr_to_eth_fifo_w9xd4096/ddr_to_eth_fifo_w9xd4096.xci
# IP: The module: 'ddr_to_eth_fifo_w9xd4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/ddr_to_eth_fifo_w9xd4096/ddr_to_eth_fifo_w9xd4096.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_to_eth_fifo_w9xd4096'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/ddr_to_eth_fifo_w9xd4096/ddr_to_eth_fifo_w9xd4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_to_eth_fifo_w9xd4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/ddr_to_eth_fifo_w9xd4096/ddr_to_eth_fifo_w9xd4096.xci
# IP: The module: 'ddr_to_eth_fifo_w9xd4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/ddr_to_eth_fifo_w9xd4096/ddr_to_eth_fifo_w9xd4096.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_to_eth_fifo_w9xd4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/software_download_zc/Vivado/vivado_my_projects_2/IC/vivado_ddrc_484_2_ddr_eth/ddrc_484_2.srcs/sources_1/ip/ddr_to_eth_fifo_w9xd4096/ddr_to_eth_fifo_w9xd4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_to_eth_fifo_w9xd4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
